#ifndef _SOUND_PRIORITIES_H_
#define _SOUND_PRIORITIES_H_

#define STARTUP_PRIORITY 0
#define MOTOR_SOUND_PRIORITY 3
#define BOMB_DROP_PRIORITY 6
#define MACHINEGUN_PRIORITY 9
#define ZOOM_PRIORITY 10

#endif
